siteTitle = "@manpenaloza"
siteDescr = "Personal Website of @manpenaloza - Freelance Web-/App Development with a marked preference for React and React-Native"
siteAuthor = "@manpenaloza"

twitterId = "manpenaloza"
googleAnalyticsId = ""
linkPrefix = "/"
twitterProfile = "https://www.twitter.com/manpenaloza"
linkedinProfile = "https://at.linkedin.com/in/penalozamanuel"

menuPoints = [
    "about",
    "timeline",
    "showroom",
    "lounge",
    "contact",
]